definitions:
  domain.BaseResponse:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  domain.ChimeCreateOrUpdateRequest:
    properties:
      chimeContent:
        type: string
      chimeTitle:
        type: string
      isPrivate:
        type: boolean
    required:
    - chimeContent
    - chimeTitle
    - isPrivate
    type: object
  domain.ChimeListResponse:
    properties:
      chimes:
        items:
          $ref: '#/definitions/domain.ChimeWithAuthor'
        type: array
      message:
        type: string
      statusCode:
        type: integer
    type: object
  domain.ChimeResponse:
    properties:
      chime:
        $ref: '#/definitions/domain.ChimeWithAuthor'
      message:
        type: string
      statusCode:
        type: integer
    type: object
  domain.ChimeWithAuthor:
    properties:
      author:
        $ref: '#/definitions/models.User'
      chimeContent:
        type: string
      chimeTitle:
        type: string
      createdAt:
        type: string
      id:
        type: string
      isPrivate:
        type: boolean
    type: object
  domain.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  domain.LoginResponse:
    properties:
      accessToken:
        type: string
      message:
        type: string
      refreshToken:
        type: string
      statusCode:
        type: integer
      user:
        $ref: '#/definitions/models.User'
    type: object
  domain.ProfileResponse:
    properties:
      message:
        type: string
      profile:
        $ref: '#/definitions/models.User'
      statusCode:
        type: integer
    type: object
  domain.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
      penName:
        type: string
      userName:
        type: string
    required:
    - email
    - password
    - userName
    type: object
  domain.SignUpResponse:
    properties:
      accessToken:
        type: string
      message:
        type: string
      refreshToken:
        type: string
      statusCode:
        type: integer
      user:
        $ref: '#/definitions/models.User'
    type: object
  domain.TokenRefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  domain.TokenRefreshResponse:
    properties:
      access_token:
        type: string
    type: object
  models.Chime:
    properties:
      author:
        type: string
      chimeContent:
        type: string
      chimeTitle:
        type: string
      createdAt:
        type: string
      id:
        type: string
      isPrivate:
        type: boolean
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      penName:
        type: string
      userName:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login/:
    post:
      consumes:
      - application/json
      description: Logs a user in by validating credentials and returning access and
        refresh tokens.
      parameters:
      - description: Login Request Payload
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful, returns access and refresh tokens
          schema:
            $ref: '#/definitions/domain.LoginResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/domain.BaseResponse'
        "401":
          description: Unauthorized - Invalid credentials or user not found
          schema:
            $ref: '#/definitions/domain.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.BaseResponse'
      summary: User Login
      tags:
      - Authentication
  /auth/signup/:
    post:
      consumes:
      - application/json
      description: Signs up a new user by validating the fields and returns their
        access token and refresh token
      parameters:
      - description: SignUp Request Payload
        in: body
        name: signUpRequest
        required: true
        schema:
          $ref: '#/definitions/domain.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Signup successful, returns access and refresh tokens
          schema:
            $ref: '#/definitions/domain.SignUpResponse'
        "400":
          description: Bad Request - Invalid or missing parameters in the request
          schema:
            $ref: '#/definitions/domain.BaseResponse'
        "409":
          description: Conflict - User already exists
          schema:
            $ref: '#/definitions/domain.BaseResponse'
        "500":
          description: Internal Server Error - Issue processing the request
          schema:
            $ref: '#/definitions/domain.BaseResponse'
      summary: User Signup
      tags:
      - Authentication
  /chimes/:
    get:
      consumes:
      - application/json
      description: Fetch all Chimes from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.ChimeListResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ChimeListResponse'
      summary: Get all Chimes
      tags:
      - Chimes
    post:
      consumes:
      - application/json
      description: Create a new chime by providing a request body with necessary details.
      parameters:
      - description: Chime Create Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.ChimeCreateOrUpdateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.ChimeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ChimeResponse'
      security:
      - BearerAuth: []
      summary: Creates a new Chime
      tags:
      - Chimes
  /chimes/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing chime by providing the chime ID
      parameters:
      - description: Chime ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/domain.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.BaseResponse'
      security:
      - BearerAuth: []
      summary: Delete an existing Chime
      tags:
      - Chimes
    put:
      consumes:
      - application/json
      description: Update an existing chime by providing the chime ID and updated
        details
      parameters:
      - description: Chime ID
        in: path
        name: id
        required: true
        type: string
      - description: Chime Update Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.ChimeCreateOrUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Chime'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ChimeResponse'
      security:
      - BearerAuth: []
      summary: Update an existing Chime
      tags:
      - Chimes
  /chimes/user/:
    get:
      consumes:
      - application/json
      description: Fetch all Chimes from logged in user from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Chime'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ChimeListResponse'
      security:
      - BearerAuth: []
      summary: Get all Chimes of logged in user
      tags:
      - Chimes
  /token/refresh/:
    post:
      consumes:
      - application/json
      description: Allows users to refresh their access token using a valid refresh
        token.
      parameters:
      - description: Refresh Token Request Payload
        in: body
        name: refreshRequest
        required: true
        schema:
          $ref: '#/definitions/domain.TokenRefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Returns a new access token
          schema:
            $ref: '#/definitions/domain.TokenRefreshResponse'
      summary: Generate a new access token using a refresh token
      tags:
      - Token
  /user/me/:
    get:
      consumes:
      - application/json
      description: Retrives the profile details of the user based on access token
      produces:
      - application/json
      responses:
        "201":
          description: Returns Profile of the user
          schema:
            $ref: '#/definitions/domain.ProfileResponse'
        "404":
          description: Profile Not Found
          schema:
            $ref: '#/definitions/domain.BaseResponse'
      security:
      - BearerAuth: []
      summary: User Me Endpoint
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: API documentation for ChimeSpace backend
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
