name: Lint and Static Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  lint:
    name: Lint and Static Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' 


      - name: Install GolangCI-Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint version

   
      - name: Run Linter
        run: |
          set -e  # Exit on error
          golangci-lint run ./... --timeout=5m


      - name: Run Go Vet (Static Analysis)
        run: |
          set -e  # Exit on error
          go vet ./...
